#!/bin/sh

if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
	echo "Usage: $0 <user_script_file>"
	exit 0
fi

SELFDIR=$(dirname "$0")

"$SELFDIR/getmeta" "$1"
java -jar "$SELFDIR/yuicompressor-2.4.7.jar" "$1"
