#!/bin/sh

if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
	echo "Usage: $0 <user_script_file> <var_name>"
	exit 0
fi

cat "$1" | egrep -m 1 "\/\/\s*\@$2\s" | sed 's/^\/\/\s*\@\w*\s*//' | sed 's/\s*$//'
