#!/bin/sh

if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
	echo "Usage: $0 <user_script_file>"
	exit 0
fi

OUT=$(cat "$1" | egrep '\/\/\s*(\=\=|\@\w)')
END=$(echo "$OUT" | egrep -n -m 1 '\/\/\s*\=\=\/UserScript\=\=' | egrep -o '^[0-9]+')
echo "$OUT" | grep -m $END /
