#!/bin/sh

if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
	echo "Usage: $0 <user_script_file>"
	exit 0
fi

SELFDIR=$(dirname "$0")
GETVAR="$SELFDIR/getmetavar"

#printf $("$GETVAR" "$1" name | sed 's/\s/\_/g')
#printf "_"
printf $("$GETVAR" "$1" version)
echo ".user.js"
