#!/bin/sh

if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
	echo "Usage: $0 <user_script_file>"
	exit 0
fi

SELFDIR=$(dirname "$0")
GETVAR="$SELFDIR/getmetavar"

IDP=$(cat "$1" | grep '\/\*\[IDP\]\*\/' | sed 's/^.*\/\*\[IDP\]\*\///' | sed 's/\/\*\[\/IDP\]\*\/.*$//' | sed "s/^\s*'//" | sed "s/'\s*$//" | sed 's/^\s*"//' | sed 's/"\s*$//')
VERSION=$("$GETVAR" "$1" version)

echo "${IDP}onVersionFound('${VERSION}');"
